# Generated by Django 3.2.9 on 2021-12-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookss', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
