# Generated by Django 3.2.9 on 2021-12-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookss', '0003_books_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
